
server:
  port: 9900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:12345/eureka/

spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  routes:
    strategy:
      path: /strategy/**
      service-id: oms-strategy-biz
    trade:
      path: /trade/**
      service-id: oms-trade-biz