server:
  port: 80

spring:
  application:
    name: oms-strategy-master
  redis:
    host: 192.168.29.131
    port: 9200
    # redis集群模式用这个配置
    #cluster:
    #  nodes: 192.168.29.131:9200, 192.168.29.132:9200
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oms?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC #Asia/Shanghai
    username: oms
    password: oms
    druid:
      initial-size: 10
      max-active: 11

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    registry-fetch-interval-seconds: 1
    service-url:
      defaultZone: http://127.0.0.1:12345/eureka/

